### ISSUE TITLE
Style quest view

### ISSUE THREAD

**Issue by mattrclark** [Mclar053/Oldschool_tools#1]
## Description
Style quest view. Not too sure on designed right yet so designs still have to be made.

## Tasks
- [ ] Design what the single quest view will look like
- [ ] Add css file for the view
- [ ] Attach css file to the header of the dom
- [ ] Add styling /classes for elements on the view
