### ISSUE TITLE
Add Items to Item table relating to quests

### ISSUE THREAD

**Issue by mattrclark** [Mclar053/Oldschool_tools#14]
## Description
Add items to the ITEMS table. This could be acheived by creating a spreadsheet of all the items in game, with the id that can be used for the grand exchange (Related Task: #7). I think this ID could be separate from the primary key.

## Tasks
- [ ] Find all items for quests
- [ ] Find the grand exchange ID and assign it to the tradeable items
- [ ] Add all items to the ITEMS table
