### ISSUE TITLE
Style all quests view

### ISSUE THREAD

**Issue by mattrclark** [Mclar053/Oldschool_tools#2]
## Description
Style all quests view. Not too sure on designed right yet so designs still have to be made.

## Tasks
- [ ] Design what the all quests view will look like
- [ ] Add css file for the view
- [ ] Attach css file to the header of the dom
- [ ] Add styling /classes for elements on the view
