### ISSUE TITLE
Add filter to all quest view

### ISSUE THREAD

**Issue by mattrclark** [Mclar053/Oldschool_tools#3]
## Description
Add filter on all quests view so the user can search and find quests based on the criteria in the filter.

Filter will be using javascript as it shouldn't require a post/get request from the server. All information has been provided to the user so they can filter from all the information they have.

Criteria include:
- Quest Name (Textbox)
- Difficulty (Dropdown)
- Length (Dropdown)
- Members (Checkbox)

## Tasks 
- [ ] Add javascript filter object
- [ ] Create inputs for filter object
- [ ] Add criteria for inputs
- [ ] Attach filter object to the view
